In [1]:
#경찰 데이터 변환

import pandas as pd
import numpy as np

In [ ]:
polices = pd.read_csv('../data/safety/policeFacilities.csv')
polices = polices[polices['시도청'] == '서울청']

mapper = {'파출소':2,'지구대':1}

polices = polices[['경찰서','관서명','구분','주소']]
polices['구분'] = polices['구분'].map(mapper)
polices['이름'] =  polices['경찰서'] +" "+  polices['관서명']
polices = polices.drop(columns=['경찰서','관서명'])
polices.head()

   구분                              주소       이름
0   1               서울특별시 중구  을지로 234  서울중부 을지
1   1             서울특별시 중구  퇴계로 375-1  서울중부 광희
2   1      서울특별시 중구  동호로 5길 15, 약수지구대  서울중부 약수
3   2  서울특별시 중구  다산로 248 (신당동, 신당파출소)  서울중부 신당
4   2               서울특별시 중구  동호로 261  서울중부 장충

In [ ]:
polices.to_csv('../export/safety/policeFacilities.csv', index=False, encoding='utf-8')  # index=False로 행 번호 제외

     구분                              주소       이름
0     1               서울특별시 중구  을지로 234  서울중부 을지
1     1             서울특별시 중구  퇴계로 375-1  서울중부 광희
2     1      서울특별시 중구  동호로 5길 15, 약수지구대  서울중부 약수
3     2  서울특별시 중구  다산로 248 (신당동, 신당파출소)  서울중부 신당
4     2               서울특별시 중구  동호로 261  서울중부 장충
..   ..                             ...      ...
238   1              서울특별시 강남구  삼성로 203  서울수서 대치
239   2            서울특별시 강남구  밤고개로1길 48  서울수서 수서
240   2              서울특별시 강남구  헌릉로 623  서울수서 대왕
241   1       서울특별시 강남구  일원로3길 35 일원파출소  서울수서 일원
242   1        서울특별시 강남구  개포로 261(1268)  서울수서 개포

[243 rows x 3 columns]